"""empty message

Revision ID: 69f398d9ab1a
Revises: 6986cb9997fe
Create Date: 2022-07-28 17:47:33.480367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f398d9ab1a'
down_revision = '6986cb9997fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('organisation', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('subscription_date', sa.DateTime(), nullable=False),
    sa.Column('report_type', sa.String(length=25), nullable=False),
    sa.Column('daily', sa.Boolean(), nullable=False),
    sa.Column('weekly', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'report_type')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_subscribers_organisation'), 'subscribers', ['organisation'], unique=False)
    op.create_index(op.f('ix_subscribers_region'), 'subscribers', ['region'], unique=False)
    op.create_index(op.f('ix_subscribers_report_type'), 'subscribers', ['report_type'], unique=False)
    op.create_index(op.f('ix_subscribers_subscription_date'), 'subscribers', ['subscription_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_subscription_date'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_report_type'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_region'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_organisation'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
